import { NewsletterData } from '../types';

const FONT_STACK = "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, sans-serif";

/**
 * Renders the newsletter adhering strictly to GitHub's markdown typography hierarchy,
 * font sizes, font weights, and spacing.
 */
export function renderNewsletterHtml(data: NewsletterData): string {
  const { formattedDate, facts } = data;

  const sectionsHtml = facts.map((fact) => {
    return `
      <!-- ## ${fact.categoryLabel} (GitHub H2 style) -->
      <h2 style="font-family: ${FONT_STACK}; font-size: 22px; font-weight: 600; line-height: 1.25; color: #1f2328; margin: 28px 0 16px 0; padding-bottom: 0.3em; border-bottom: 1px solid #d0d7de;">
        ${fact.emoji} ${fact.categoryLabel}
      </h2>

      <!-- ### ${fact.title} (GitHub H3 style) -->
      <h3 style="font-family: ${FONT_STACK}; font-size: 17px; font-weight: 600; line-height: 1.25; color: #1f2328; margin: 18px 0 10px 0;">
        ${fact.title}
      </h3>

      <!-- > Fact Blockquote (GitHub Blockquote style) -->
      <blockquote style="margin: 0 0 14px 0; padding: 0 1em; color: #57606a; border-left: 0.25em solid #d0d7de; font-family: ${FONT_STACK}; font-size: 15px; font-weight: 400; line-height: 1.6;">
        <p style="margin: 0; color: #1f2328; font-weight: 500;">
          ${fact.fact}
        </p>
      </blockquote>

      <!-- Detail Paragraph (GitHub Body style) -->
      <p style="margin: 0 0 16px 0; font-family: ${FONT_STACK}; font-size: 15px; font-weight: 400; line-height: 1.6; color: #1f2328;">
        ${fact.detail}
      </p>
    `;
  }).join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>InToday · ${formattedDate}</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
  <style type="text/css">
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
    body, table, td, p, h1, h2, h3, blockquote, span {
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, sans-serif !important;
    }
  </style>
</head>
<body style="margin: 0; padding: 32px 16px; background-color: #ffffff; color: #1f2328; font-family: ${FONT_STACK}; font-size: 15px; font-weight: 400; line-height: 1.6; -webkit-font-smoothing: antialiased;">
  
  <div style="max-width: 680px; margin: 0 auto; background-color: #ffffff;">
    
    <!-- # InToday (GitHub H1 style) -->
    <h1 style="font-family: ${FONT_STACK}; font-size: 28px; font-weight: 600; line-height: 1.25; color: #1f2328; margin: 0 0 16px 0; padding-bottom: 0.3em; border-bottom: 1px solid #d0d7de;">
      InToday &middot; ${formattedDate}
    </h1>

    <!-- > Subtitle Quote -->
    <blockquote style="margin: 0 0 24px 0; padding: 0 1em; color: #57606a; border-left: 0.25em solid #d0d7de; font-family: ${FONT_STACK}; font-size: 14px; font-weight: 400; line-height: 1.5;">
      <p style="margin: 0;">
        Daily curated micro-insights across everyday reality, economics, law, and psychology.
      </p>
    </blockquote>

    <!-- Content Sections -->
    ${sectionsHtml}

    <!-- Footer Horizontal Rule & Metadata -->
    <hr style="height: 1px; padding: 0; margin: 36px 0 16px 0; background-color: #d0d7de; border: 0;" />
    
    <p style="margin: 0 0 4px 0; font-size: 12px; font-weight: 400; color: #656d76; font-family: ${FONT_STACK};">
      Generated by <strong style="font-weight: 600; color: #1f2328;">InToday</strong> &middot; Powered by OrcaRouter &amp; Resend
    </p>
    <p style="margin: 0; font-size: 11px; font-weight: 400; color: #8c959f; font-family: ${FONT_STACK};">
      Private edition &middot; Sent to subscriber list
    </p>

  </div>

</body>
</html>`;
}

/**
 * Plaintext version for email clients that do not support HTML.
 */
export function renderNewsletterText(data: NewsletterData): string {
  const { formattedDate, facts } = data;

  let text = `# InToday · ${formattedDate}\n\n`;
  text += `> Daily curated micro-insights across everyday reality, economics, law, and psychology.\n\n`;

  for (const factsItem of facts) {
    text += `## ${factsItem.emoji} ${factsItem.categoryLabel}\n\n`;
    text += `### ${factsItem.title}\n\n`;
    text += `> ${factsItem.fact}\n\n`;
    text += `${factsItem.detail}\n\n`;
    text += `---\n\n`;
  }

  text += `Generated by InToday · Powered by OrcaRouter & Resend\n`;
  return text;
}
