import { NewsletterData } from '../types';

/**
 * Renders the newsletter as a pure, minimal, GitHub README markdown-style HTML email.
 */
export function renderNewsletterHtml(data: NewsletterData): string {
  const { formattedDate, facts } = data;

  const sectionsHtml = facts.map((fact) => {
    return `
      <!-- ${fact.categoryLabel} Section -->
      <h2 style="font-size: 20px; font-weight: 600; line-height: 1.3; color: #1f2328; padding-bottom: 7px; border-bottom: 1px solid #d0d7de; margin: 32px 0 16px 0;">
        ${fact.emoji} ${fact.categoryLabel}
      </h2>

      <h3 style="font-size: 16px; font-weight: 600; line-height: 1.4; color: #1f2328; margin: 16px 0 10px 0;">
        ${fact.title}
      </h3>

      <blockquote style="margin: 0 0 12px 0; padding: 0 1em; color: #24292f; border-left: 0.25em solid #d0d7de; font-size: 15px; line-height: 1.6;">
        <p style="margin: 0; font-weight: 500;">
          ${fact.fact}
        </p>
      </blockquote>

      <p style="margin: 0 0 16px 0; font-size: 14.5px; line-height: 1.65; color: #1f2328;">
        ${fact.detail}
      </p>
    `;
  }).join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>InToday · ${formattedDate}</title>
</head>
<body style="margin: 0; padding: 24px 16px; background-color: #ffffff; color: #1f2328; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji'; font-size: 15px; line-height: 1.6; -webkit-font-smoothing: antialiased;">
  
  <div style="max-width: 640px; margin: 0 auto; background-color: #ffffff;">
    
    <!-- Title / H1 -->
    <h1 style="font-size: 26px; font-weight: 600; line-height: 1.25; color: #1f2328; margin: 0 0 12px 0; padding-bottom: 10px; border-bottom: 1px solid #d0d7de;">
      InToday &middot; ${formattedDate}
    </h1>

    <blockquote style="margin: 0 0 24px 0; padding: 0 1em; color: #57606a; border-left: 0.25em solid #d0d7de; font-size: 14px; line-height: 1.5;">
      <p style="margin: 0;">
        Daily curated micro-insights across everyday reality, economics, law, and psychology.
      </p>
    </blockquote>

    <!-- Content Sections -->
    ${sectionsHtml}

    <!-- Footer HR and Signature -->
    <hr style="height: 1px; padding: 0; margin: 36px 0 16px 0; background-color: #d0d7de; border: 0;" />
    
    <p style="margin: 0 0 6px 0; font-size: 12px; color: #656d76; font-family: ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, 'Liberation Mono', monospace;">
      Generated by <code>InToday</code> &middot; Powered by OrcaRouter &amp; Resend
    </p>
    <p style="margin: 0; font-size: 11px; color: #8c959f; font-family: ui-monospace, SFMono-Regular, 'SF Mono', Menlo, Consolas, 'Liberation Mono', monospace;">
      Private edition &middot; Sent to subscriber list
    </p>

  </div>

</body>
</html>`;
}

/**
 * Plaintext version for email clients that do not support HTML.
 */
export function renderNewsletterText(data: NewsletterData): string {
  const { formattedDate, facts } = data;

  let text = `# InToday · ${formattedDate}\n\n`;
  text += `> Daily curated micro-insights across everyday reality, economics, law, and psychology.\n\n`;

  for (const fact of facts) {
    text += `## ${fact.emoji} ${fact.categoryLabel}\n\n`;
    text += `### ${fact.title}\n\n`;
    text += `> ${fact.fact}\n\n`;
    text += `${fact.detail}\n\n`;
    text += `---\n\n`;
  }

  text += `Generated by InToday · Powered by OrcaRouter & Resend\n`;
  return text;
}
